# Application Pipeline (app-pipeline.yml)
stages:
  - build
  - test
  - trigger

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# Security scanning templates
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml


# Maven cache reloaded on pom.xml
.maven-cache: &maven-cache
  image: maven:3-eclipse-temurin-17
  cache:
    key:
      files:
        - pom.xml
    paths:
      - $CI_PROJECT_DIR/.m2/repository
    policy: pull-push

# Template for using maven
.maven-config: &maven-config
  needs: [build-spring]
  <<: *maven-cache

# Creating the package skipping the tests
build-spring:
  stage: build
  <<: *maven-cache
  script:
    - mvn clean package -DskipTests
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_MERGE_REQUEST_ID
  artifacts:
    paths:
      - target/testing-web-complete-0.0.1-SNAPSHOT.jar
    expire_in: 1 day



# Unit test skipping integration tests
unit-test-spring:
  stage: test
  <<: *maven-config
  script:
    - mvn test jacoco:report -DskipITs
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_MERGE_REQUEST_ID
  artifacts:
    reports:
      junit: $CI_PROJECT_DIR/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: $CI_PROJECT_DIR/target/site/jacoco/jacoco.xml
    paths:
      - target/site/jacoco/
    expire_in: 1 week
  coverage: '/Total.*?([0-9]{1,3})%/'



# Integration tests skipping unit tests
integration-test-spring:
  stage: test
  <<: *maven-config
  needs: [unit-test-spring]
  script:
    - mvn verify -DskipUnitTests
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_MERGE_REQUEST_ID
  artifacts:
    reports:
      junit: $CI_PROJECT_DIR/target/failsafe-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: $CI_PROJECT_DIR/target/site/jacoco-it/jacoco.xml
    paths:
      - $CI_PROJECT_DIR/target/site/jacoco-it/jacoco.xml
    expire_in: 1 week

trigger-docker-pipeline:
  stage: trigger
  trigger:
    include: pipelines/docker-pipeline.yml
    strategy: depend
  rules:
    - changes:
        - Dockerfile
        - src/**/*
        - .gitlab-ci.yml
        - docker-pipeline.yml
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

trigger-quality-pipeline:
  stage: trigger
  trigger:
    include: pipelines/quality-pipeline.yml
    strategy: depend
  rules:
    - changes:
        - src/**/*
        - pom.xml
        - .gitlab-ci.yml
        - quality-pipeline.yml
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
